apiVersion: apps/v1
kind: Deployment
metadata:
  name: netlify-ml
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: ml
    app.kubernetes.io/part-of: netlify-extension
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netlify-extension
      app.kubernetes.io/component: ml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netlify-extension
        app.kubernetes.io/component: ml
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: netlify-extension
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: ml
          image: ghcr.io/candlefish-enterprise/netlify-extension-ml:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MODEL_PATH
              value: "/app/models"
            - name: WORKERS
              value: "2"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: netlify-extension-config
                  key: LOG_LEVEL
            - name: ML_MODEL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: netlify-extension-config
                  key: ML_MODEL_VERSION
            - name: ML_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: netlify-extension-config
                  key: ML_BATCH_SIZE
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: models
              mountPath: /app/models
            - name: cache
              mountPath: /app/cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: models
          emptyDir: {}
        - name: cache
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - ml
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: netlify-ml-service
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: ml
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: ml
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: netlify-ml-hpa
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netlify-ml
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Percent
          value: 25
          periodSeconds: 120
