apiVersion: v1
kind: Secret
metadata:
  name: netlify-extension-secrets
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: configuration
type: Opaque
stringData:
  # Database credentials (will be overridden by external-secrets in production)
  DATABASE_URL: "postgresql://netlify_user:changeme@postgres:5432/netlify_extension"
  REDIS_URL: "redis://redis:6379/0"

  # API Keys (placeholders - will be managed by external-secrets)
  NETLIFY_API_TOKEN: "placeholder-netlify-token"
  GITHUB_TOKEN: "placeholder-github-token"

  # Encryption keys
  JWT_SECRET: "placeholder-jwt-secret"
  ENCRYPTION_KEY: "placeholder-encryption-key"

  # Third-party service credentials
  SLACK_WEBHOOK_URL: "placeholder-slack-webhook"
  SENDGRID_API_KEY: "placeholder-sendgrid-key"

  # Monitoring credentials
  PROMETHEUS_PASSWORD: "placeholder-prometheus-password"
  GRAFANA_ADMIN_PASSWORD: "placeholder-grafana-password"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netlify-extension-aws-secrets
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: configuration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: netlify-extension-secrets
    creationPolicy: Merge
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: candlefish/netlify-extension/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: candlefish/netlify-extension/redis-url
    - secretKey: NETLIFY_API_TOKEN
      remoteRef:
        key: candlefish/netlify/api-token
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: candlefish/github/token
    - secretKey: JWT_SECRET
      remoteRef:
        key: candlefish/netlify-extension/jwt-secret
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: candlefish/netlify-extension/encryption-key
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: candlefish/slack/webhook-url
    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: candlefish/sendgrid/api-key
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: configuration
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  labels:
    app.kubernetes.io/name: netlify-extension
    app.kubernetes.io/component: configuration
type: Opaque
stringData:
  access-key-id: "placeholder-aws-access-key"
  secret-access-key: "placeholder-aws-secret-key"
