# PostgreSQL Database for Candlefish AI
app = "candlefish-postgres"
primary_region = "sjc"

[build]
  image = "postgres:15-alpine"

[env]
  POSTGRES_USER = "candlefish"
  POSTGRES_DB = "candlefish_collaboration"
  PGDATA = "/var/lib/postgresql/data/pgdata"

# Volume configuration for persistent data
[[mounts]]
  source = "postgres_data"
  destination = "/var/lib/postgresql/data"

# VM configuration
[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# PostgreSQL service
[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 5432

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
