apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-resources-backend
  namespace: claude-resources
  labels:
    app: backend
    component: service-account
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: claude-resources-frontend
  namespace: claude-resources
  labels:
    app: frontend
    component: service-account
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: claude-resources
  name: claude-resources-backend-role
rules:
# Allow reading pods for health checks
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Allow reading configmaps and secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
# Allow creating events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: claude-resources-backend-rolebinding
  namespace: claude-resources
subjects:
- kind: ServiceAccount
  name: claude-resources-backend
  namespace: claude-resources
roleRef:
  kind: Role
  name: claude-resources-backend-role
  apiGroup: rbac.authorization.k8s.io

---
# External Secrets Operator Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: claude-resources
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ExternalSecretsOperatorRole

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: claude-resources
  name: external-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
  namespace: claude-resources
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: claude-resources
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io
