# Netlify configuration for Candlefish AI Documentation Site
[build]
  base = "apps/docs-site"
  publish = "out"
  command = "cd ../.. && pnpm brand:sync && pnpm turbo build --filter=apps/docs-site"

  [build.environment]
    NODE_VERSION = "18.17.0"
    PNPM_VERSION = "8.15.6"
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"
    GENERATE_SOURCEMAP = "false"
    NODE_OPTIONS = "--max-old-space-size=4096"

# Production deployment
[context.production]
  [context.production.environment]
    NEXT_PUBLIC_API_URL = "https://api.candlefish.ai"
    NEXT_PUBLIC_WS_URL = "wss://ws.candlefish.ai"
    NEXT_PUBLIC_APP_URL = "https://app.candlefish.ai"
    NEXT_PUBLIC_PARTNERS_URL = "https://partners.candlefish.ai"
    NEXT_PUBLIC_ENVIRONMENT = "production"
    NEXT_PUBLIC_SENTRY_DSN = "$SENTRY_DSN"
    NEXT_PUBLIC_ANALYTICS_ID = "$GA_TRACKING_ID"

# Staging deployment
[context.deploy-preview]
  [context.deploy-preview.environment]
    NEXT_PUBLIC_API_URL = "https://api-staging.candlefish.ai"
    NEXT_PUBLIC_WS_URL = "wss://ws-staging.candlefish.ai"
    NEXT_PUBLIC_ENVIRONMENT = "staging"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://*.candlefish.ai https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' https://*.candlefish.ai data: https:;
      connect-src 'self' https://*.candlefish.ai wss://*.candlefish.ai;
      frame-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    '''

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse"
