# Gitleaks configuration for candlefish-ai
title = "candlefish-ai gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Allowlisted files and paths"
paths = [
  '''\.lock$''',
  '''node_modules''',
  '''vendor''',
  '''\.git''',
  '''\.venv''',
  '''venv''',
  '''dist''',
  '''build''',
  '''\.next''',
  '''coverage''',
  '''\.pytest_cache''',
  '''__pycache__''',
]

# Add whitelist for test/placeholder values found in the codebase
regexes = [
  '''example\.com''',
  '''test[_\-]?key''',
  '''dummy[_\-]?secret''',
  '''placeholder''',
  '''your[_\-]?api[_\-]?key''',
  '''REPLACE_WITH_''',
  '''test.*password''',
  '''expired-token''',
  '''refreshed-token''',
  '''McIntosh2025Legal''',
  '''test-secret-key''',
  '''query-token''',
  '''generated-jwt-token''',
  '''valid-test-token''',
  '''invalid\.jwt\.token''',
  '''testPassword123!''',
  '''test-jwt-secret-key''',
  '''e2e-test-secret''',
  '''user-token-123''',
  '''user1-token''',
  '''wrongpassword''',
  '''TestUser123!''',
  '''jwt_token_here''',
  '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9''',
  '''REPLACE_WITH_SECURE_PASSWORD''',
  '''REPLACE_WITH_SECURE_TOKEN''',
  '''REPLACE_WITH_ACTUAL_VALUE''',
  '''REPLACE_WITH_32_CHAR_SECRET''',
  '''SecurePassword123!''',
  '''\$\{[A-Z_]+\}''',  # Environment variables
  '''process\.env\.[A-Z_]+''',  # Node env vars
]

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-\_]{90,}'''
tags = ["api-key", "anthropic"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
tags = ["api-key", "openai"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "access-key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"]?[0-9a-zA-Z\/+]{40}['\"]?'''
tags = ["aws", "secret"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

[[rules]]
id = "github-oauth"
description = "GitHub OAuth Token"
regex = '''gho_[0-9a-zA-Z]{36}'''
tags = ["github", "oauth"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'''
tags = ["private-key", "sensitive"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_\-\s]?key|apikey)['\"]?\s*[:=]\s*['\"]?([a-zA-Z0-9\-\_]{32,})'''
tags = ["api-key", "generic"]
entropy = 4.5

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)(secret|password|passwd|pwd|token|auth)['\"]?\s*[:=]\s*['\"]?([a-zA-Z0-9\-\_\$\{\}]{8,})'''
tags = ["secret", "generic"]
entropy = 4.0
