---
# Pre-commit hooks for candlefish-ai
# Run: pre-commit install
# Manual: pre-commit run --all-files

repos:
  # Security scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(projects/fogg/calendar/|apps/rtpm-api/test_client\.py)
      - id: ruff-format
        exclude: ^(projects/fogg/calendar/|apps/rtpm-api/test_client\.py)

  # JavaScript/TypeScript - Disabled until ESLint v9 config is properly set up
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v9.8.0
  #   hooks:
  #     - id: eslint
  #       files: \.(js|jsx|ts|tsx)$
  #       additional_dependencies:
  #         - eslint@9.8.0
  #         - eslint-config-prettier@9.1.0
  #       exclude: ^(node_modules|dist|build)/

  # YAML validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: '\.yml$|template\.yaml$|serverless\.yml$|cloudwatch-alarms\.yml$|projects/paintbox/\.pre-commit-config\.yaml$'
      - id: check-json
        exclude: 'tsconfig.*\.json$'  # Exclude TypeScript config files (may have comments)
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '\.(lock|zip|tar\.gz|png|jpg|jpeg|gif|ico|pdf|bin)$'
      - id: trailing-whitespace
        exclude: '\.(lock|zip|tar\.gz|png|jpg|jpeg|gif|ico|pdf|bin|md)$'
      - id: check-added-large-files
        args: [--maxkb=10000]  # Increase limit to 10MB
        exclude: '\.serverless/.*\.zip$'  # Exclude serverless build artifacts
      - id: check-merge-conflict
      - id: detect-private-key

  # Markdown - Disabled due to extensive formatting issues that would require major changes
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.41.0
  #   hooks:
  #     - id: markdownlint
  #       args: [--fix]

  # Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [-e, SC2162, -e, SC2086, -e, SC2034, -e, SC2155, -e, SC2129, -e, SC2181, -e, SC1091, -e, SC2012, -e, SC2164, -e, SC2044, -e, SC2046, -e, SC2103, -e, SC2002, -e, SC2236, -e, SC2317, -e, SC2015, -e, SC2004, -e, SC1083, -e, SC2016, -e, SC2207, -e, SC2116, -e, SC2145, -e, SC2206, -e, SC2124]
        exclude: ^(terminal-backup/|node_modules/|\.netlify/|apps/website/candlefish-production/|public/docs/privileged/)

# Local hooks
  - repo: local
    hooks:
      - id: no-direct-secrets
        name: Block direct secrets
        entry: "(?i)(api[_-]?key|secret|token|password|pwd|auth|credential)\\s*=\\s*[\"'][^\"']{10,}"
        language: pygrep
        types: [text]
        exclude: '\.(md|txt|lock|example|sample|test|spec)$|__tests__/|\.tfvars$|test_client\.py$|\.spec\.(ts|js)$|\.test\.(ts|js)$|security-audit\.ts$|candlefish_update_.*\.html$|claude-deploy-authenticated\.html$|global-setup\.ts$|examples\.ts$|test-api\.sh$|deploy.*\.sh$|netlify-deploy-api\.sh$|db-migrate\.sh$|error-handling\.ts$'
