# ************************************************
# Netlify TOML Configuration - Monorepo Root
# ************************************************

# This is the root configuration for the monorepo
# Individual apps have their own netlify.toml files

[build]
  # Default to the website app
  base = "apps/website"
  publish = "."
  # No build needed for static HTML

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Context-specific configurations
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }