# ************************************************
# Netlify TOML Configuration - Monorepo Root
# ************************************************

# This is the root configuration for the monorepo
# Individual apps have their own netlify.toml files

[build]
  # Default to the website app
  base = "apps/website"
  publish = "dist"
  command = "pnpm install && pnpm build"

# Redirect root domain to website app
[[redirects]]
  from = "/*"
  to = "https://candlefish.ai/:splat"
  status = 200
  force = false

# Context-specific configurations
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }