# ************************************************
# Netlify TOML Configuration - API Test Dashboard
# ************************************************

[build]
  base = "apps/website"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# Serve React app with SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


# Guard privileged family documents behind auth entry and Edge validation
[[redirects]]
  from = "/docs/privileged/family/*"
  to = "/docs/privileged/family/index.html"
  status = 200
  force = true

# Context-specific configurations
[context.production]
  environment = { NODE_ENV = "production", CORS_ORIGINS = "https://candlefish.ai,https://www.candlefish.ai,https://dashboard.candlefish.ai" }

[context.deploy-preview]
  environment = { NODE_ENV = "development", CORS_ORIGINS = "*" }

[context.branch-deploy]
  environment = { NODE_ENV = "development", CORS_ORIGINS = "*" }

[[headers]]
  for = "/docs/privileged/family/*"
  [headers.values]
    X-Robots-Tag = "noindex, noarchive, nosnippet, noimageindex"
    Cache-Control = "private, max-age=60"

[[edge_functions]]
  path = "/docs/privileged/family/*"
  function = "validate-family-auth"
