# ************************************************
# Netlify TOML Configuration - API Test Dashboard
# ************************************************

[build]
  base = "apps/website"
  publish = "."
  command = "echo 'No build step required for test page'"
  functions = "netlify/functions"

# Serve test page as the default
[[redirects]]
  from = "/"
  to = "/test-fetch.html"
  status = 200

# Serve static HTML files directly
[[redirects]]
  from = "/test-fetch.html"
  to = "/test-fetch.html"
  status = 200
  force = true

[[redirects]]
  from = "/claude-code-deploy.html"
  to = "/claude-code-deploy.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy.html"
  to = "/privacy.html"
  status = 200
  force = true

[[redirects]]
  from = "/terms.html"
  to = "/terms.html"
  status = 200
  force = true

# Context-specific configurations
[context.production]
  environment = { NODE_ENV = "production", CORS_ORIGINS = "https://candlefish.ai,https://www.candlefish.ai,https://dashboard.candlefish.ai" }

[context.deploy-preview]
  environment = { NODE_ENV = "development", CORS_ORIGINS = "*" }

[context.branch-deploy]
  environment = { NODE_ENV = "development", CORS_ORIGINS = "*" }