# External Secrets Operator configuration for HashiCorp Vault integration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: paintbox
spec:
  provider:
    vault:
      server: "https://vault.paintbox.candlefish.ai"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "paintbox-role"
          serviceAccountRef:
            name: "external-secrets-sa"
---
# Apollo Studio API Key
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apollo-key
  namespace: paintbox
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: apollo-key
    creationPolicy: Owner
  data:
  - secretKey: APOLLO_KEY
    remoteRef:
      key: paintbox/apollo
      property: api_key
---
# Database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: paintbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
  data:
  - secretKey: ESTIMATES_DATABASE_URL
    remoteRef:
      key: paintbox/databases
      property: estimates_url
  - secretKey: CUSTOMERS_DATABASE_URL
    remoteRef:
      key: paintbox/databases
      property: customers_url
  - secretKey: PROJECTS_DATABASE_URL
    remoteRef:
      key: paintbox/databases
      property: projects_url
  - secretKey: INTEGRATIONS_DATABASE_URL
    remoteRef:
      key: paintbox/databases
      property: integrations_url
  - secretKey: REDIS_URL
    remoteRef:
      key: paintbox/databases
      property: redis_url
---
# External API credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-api-keys
  namespace: paintbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: external-api-keys
    creationPolicy: Owner
  data:
  # Salesforce
  - secretKey: SALESFORCE_CLIENT_ID
    remoteRef:
      key: paintbox/salesforce
      property: client_id
  - secretKey: SALESFORCE_CLIENT_SECRET
    remoteRef:
      key: paintbox/salesforce
      property: client_secret
  - secretKey: SALESFORCE_USERNAME
    remoteRef:
      key: paintbox/salesforce
      property: username
  - secretKey: SALESFORCE_PASSWORD
    remoteRef:
      key: paintbox/salesforce
      property: password
  - secretKey: SALESFORCE_SECURITY_TOKEN
    remoteRef:
      key: paintbox/salesforce
      property: security_token
  # Company Cam
  - secretKey: COMPANY_CAM_API_KEY
    remoteRef:
      key: paintbox/companycam
      property: api_key
  - secretKey: COMPANY_CAM_API_SECRET
    remoteRef:
      key: paintbox/companycam
      property: api_secret
  # Weather API
  - secretKey: WEATHER_API_KEY
    remoteRef:
      key: paintbox/weather
      property: api_key
---
# JWT secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secrets
  namespace: paintbox
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: jwt-secrets
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: paintbox/jwt
      property: secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: paintbox/jwt
      property: refresh_secret
---
# Service Account for External Secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: paintbox
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/paintbox-external-secrets-role
---
# Vault auth configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-auth-config
  namespace: paintbox
data:
  vault-auth.yaml: |
    vault:
      address: "https://vault.paintbox.candlefish.ai"
      kubernetes:
        role: "paintbox-role"
        jwt_path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      auth_method: "kubernetes"
