[[redirects]]
  from = "/docs/privileged/family/*"
  to = "/docs/privileged/family/index.html"
  status = 200
  force = true
  conditions = { Role = ["admin", "core-family", "extended-family", "sensitive-legal"] }

[[redirects]]
  from = "/docs/privileged/family/*"
  to = "/docs/privileged/family/login.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex, noarchive, nosnippet, noimageindex"