service: candlefish-employee-setup-lean

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 512  # Small memory for cost savings
  timeout: 30

  environment:
    STAGE: ${self:provider.stage}
    SECRETS_PREFIX: ${self:service}-${self:provider.stage}
    ENABLE_CONTRACTOR_ACCESS: true
    MAX_TEAM_SIZE: 20
    AWS_REGION: ${self:provider.region}
    CORS_ORIGIN: "*"
    NODE_ENV: production
    GRAPHQL_ENDPOINT: /graphql
    WEBSOCKET_ENDPOINT: !Ref WebSocketApi

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
            - secretsmanager:CreateSecret
            - secretsmanager:UpdateSecret
            - secretsmanager:RotateSecret
            - secretsmanager:ListSecrets
          Resource:
            - arn:aws:secretsmanager:${self:provider.region}:*:secret:${self:service}-${self:provider.stage}/*
        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:Encrypt
          Resource: "*"
        - Effect: Allow
          Action:
            - cloudwatch:PutMetricData
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-*
        - Effect: Allow
          Action:
            - dax:GetItem
            - dax:PutItem
            - dax:UpdateItem
            - dax:DeleteItem
            - dax:Query
            - dax:Scan
            - dax:BatchGetItem
            - dax:BatchWriteItem
          Resource:
            - arn:aws:dax:${self:provider.region}:*:cache/${self:service}-${self:provider.stage}-dax
        - Effect: Allow
          Action:
            - execute-api:ManageConnections
          Resource:
            - arn:aws:execute-api:${self:provider.region}:*:*/prod/*/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*

functions:
  # Health check - Always free tier
  health:
    handler: src/handlers/health.handler
    events:
      - http:
          path: /health
          method: get
          cors: true

  # GraphQL API - Main endpoint for all GraphQL operations
  graphql:
    handler: src/handlers/graphql.handler
    memorySize: 1024  # Higher memory for GraphQL processing
    timeout: 30
    reservedConcurrency: 50  # Allow up to 50 concurrent GraphQL requests
    events:
      - http:
          path: /graphql
          method: post
          cors: true
      - http:
          path: /graphql
          method: get
          cors: true
    environment:
      USERS_TABLE: ${self:service}-${self:provider.stage}-users
      CONTRACTORS_TABLE: ${self:service}-${self:provider.stage}-contractors
      REFRESH_TOKENS_TABLE: ${self:service}-${self:provider.stage}-refresh-tokens
      AUDIT_TABLE: ${self:service}-${self:provider.stage}-audit
      CONFIG_TABLE: ${self:service}-${self:provider.stage}-config
      DAX_ENDPOINT: !GetAtt DaxCluster.ClusterDiscoveryEndpoint
      CACHE_TTL: 300
      MAX_QUERY_COMPLEXITY: 1000
      MAX_QUERY_DEPTH: 10

  # GraphQL Health Check
  graphqlHealth:
    handler: src/handlers/graphql.health
    events:
      - http:
          path: /graphql/health
          method: get
          cors: true

  # Authentication - Called rarely
  auth:
    handler: src/handlers/auth.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
      - http:
          path: /auth/refresh
          method: post
          cors: true
      - http:
          path: /auth/logout
          method: post
          cors: true

  # Employee/Contractor Management
  manageUsers:
    handler: src/handlers/users.handler
    events:
      - http:
          path: /users
          method: get
          cors: true
          authorizer: authVerify
      - http:
          path: /users
          method: post
          cors: true
          authorizer: authVerify
      - http:
          path: /users/{id}
          method: get
          cors: true
          authorizer: authVerify
      - http:
          path: /users/{id}
          method: put
          cors: true
          authorizer: authVerify
      - http:
          path: /users/{id}
          method: delete
          cors: true
          authorizer: authVerify

  # Contractor Temporary Access
  contractorAccess:
    handler: src/handlers/contractors.handler
    events:
      - http:
          path: /contractors/invite
          method: post
          cors: true
          authorizer: authVerify
      - http:
          path: /contractors/access/{token}
          method: get
          cors: true
      - http:
          path: /contractors/revoke/{id}
          method: post
          cors: true
          authorizer: authVerify

  # AWS Secrets Manager Interface
  secrets:
    handler: src/handlers/secrets.handler
    reservedConcurrency: 2  # Limit concurrent executions for cost
    events:
      - http:
          path: /secrets
          method: get
          cors: true
          authorizer: authVerify
      - http:
          path: /secrets
          method: post
          cors: true
          authorizer: authVerify
      - http:
          path: /secrets/{name}
          method: get
          cors: true
          authorizer: authVerify
      - http:
          path: /secrets/{name}
          method: put
          cors: true
          authorizer: authVerify
      - http:
          path: /secrets/{name}
          method: delete
          cors: true
          authorizer: authVerify

  # Secret Rotation - Runs monthly
  rotateSecrets:
    handler: src/handlers/rotation.handler
    events:
      - schedule:
          rate: rate(30 days)
          description: Rotate secrets monthly

  # Configuration Management
  config:
    handler: src/handlers/config.handler
    events:
      - http:
          path: /config
          method: get
          cors: true
          authorizer: authVerify
      - http:
          path: /config
          method: put
          cors: true
          authorizer: authVerify

  # Claude Integration (via stored prompts, no API calls)
  claudeAssist:
    handler: src/handlers/claude.handler
    timeout: 60  # Longer timeout for complex operations
    events:
      - http:
          path: /assist/onboarding
          method: post
          cors: true
          authorizer: authVerify
      - http:
          path: /assist/setup
          method: post
          cors: true
          authorizer: authVerify

  # Audit Logging
  auditLog:
    handler: src/handlers/audit.handler
    events:
      - http:
          path: /audit
          method: get
          cors: true
          authorizer: authVerify

  # Custom Authorizer
  authVerify:
    handler: src/handlers/authorizer.handler

  # Cleanup expired contractor access (daily)
  cleanupContractors:
    handler: src/handlers/cleanup.handler
    events:
      - schedule:
          rate: rate(1 day)
          description: Clean up expired contractor access

  # WebSocket Functions for GraphQL Subscriptions
  websocketConnect:
    handler: src/handlers/websocket.connect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: src/handlers/websocket.disconnect
    events:
      - websocket:
          route: $disconnect

  websocketMessage:
    handler: src/handlers/websocket.message
    events:
      - websocket:
          route: $default

  websocketPing:
    handler: src/handlers/websocket.ping
    events:
      - websocket:
          route: ping

resources:
  Resources:
    # DynamoDB Tables (Pay-per-request for cost optimization)
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        BillingMode: PAY_PER_REQUEST  # No monthly minimum
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        SSESpecification:
          SSEEnabled: true

    ContractorsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-contractors
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
          - AttributeName: expiresAt
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: token-index
            KeySchema:
              - AttributeName: token
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: expiry-index
            KeySchema:
              - AttributeName: expiresAt
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    RefreshTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-refresh-tokens
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: expiresAt
            AttributeType: N
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: expiresAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        SSESpecification:
          SSEEnabled: true

    AuditTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-audit
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: timestamp-index
            KeySchema:
              - AttributeName: timestamp
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: user-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-config
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true

    # DynamoDB DAX Cluster for caching
    DaxSubnetGroup:
      Type: AWS::DAX::SubnetGroup
      Properties:
        SubnetGroupName: ${self:service}-${self:provider.stage}-dax-subnet-group
        Description: DAX subnet group for GraphQL caching
        SubnetIds:
          - !Ref DaxSubnet1
          - !Ref DaxSubnet2

    DaxCluster:
      Type: AWS::DAX::Cluster
      Properties:
        ClusterName: ${self:service}-${self:provider.stage}-dax
        Description: DAX cluster for GraphQL caching
        NodeType: dax.t3.small  # Cost-optimized node type
        ReplicationFactor: 1  # Single node for cost savings
        IAMRoleARN: !GetAtt DaxServiceRole.Arn
        SubnetGroupName: !Ref DaxSubnetGroup
        SecurityGroupIds:
          - !Ref DaxSecurityGroup

    DaxServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: dax.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

    DaxSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for DAX cluster
        VpcId: !Ref DaxVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 8111
            ToPort: 8111
            SourceSecurityGroupId: !Ref DaxClientSecurityGroup

    DaxVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: true
        EnableDnsSupport: true

    DaxSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref DaxVPC
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: !Select [0, !GetAZs ""]

    DaxSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref DaxVPC
        CidrBlock: 10.0.2.0/24
        AvailabilityZone: !Select [1, !GetAZs ""]

    DaxClientSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for DAX clients
        VpcId: !Ref DaxVPC

    # WebSocket API for GraphQL Subscriptions
    WebSocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:service}-${self:provider.stage}-websocket
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: $request.body.action
        Description: WebSocket API for GraphQL subscriptions

    # S3 Bucket for static hosting (frontend)
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-web
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: false  # Allow bucket policy for static website hosting
          IgnorePublicAcls: true
          RestrictPublicBuckets: false  # Allow public access via bucket policy only
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000

    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Sub '${WebsiteBucket.Arn}/*'


  Outputs:
    ApiEndpoint:
      Description: API Gateway endpoint URL
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: ApiGatewayRestApi
            - '.execute-api.'
            - ${self:provider.region}
            - '.amazonaws.com/'
            - ${self:provider.stage}
      Export:
        Name: ${self:service}-${self:provider.stage}-api-endpoint

    WebsiteURL:
      Description: S3 Website URL
      Value: !GetAtt WebsiteBucket.WebsiteURL
      Export:
        Name: ${self:service}-${self:provider.stage}-website-url

    S3BucketName:
      Description: S3 bucket for static website
      Value: !Ref WebsiteBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-bucket

    GraphQLEndpoint:
      Description: GraphQL endpoint URL
      Value:
        Fn::Join:
          - ''
          - - 'https://'
            - Ref: ApiGatewayRestApi
            - '.execute-api.'
            - ${self:provider.region}
            - '.amazonaws.com/'
            - ${self:provider.stage}
            - '/graphql'
      Export:
        Name: ${self:service}-${self:provider.stage}-graphql-endpoint

    WebSocketEndpoint:
      Description: WebSocket API endpoint for GraphQL subscriptions
      Value:
        Fn::Join:
          - ''
          - - 'wss://'
            - Ref: WebSocketApi
            - '.execute-api.'
            - ${self:provider.region}
            - '.amazonaws.com/'
            - ${self:provider.stage}
      Export:
        Name: ${self:service}-${self:provider.stage}-websocket-endpoint

    DaxEndpoint:
      Description: DAX cluster endpoint
      Value: !GetAtt DaxCluster.ClusterDiscoveryEndpoint
      Export:
        Name: ${self:service}-${self:provider.stage}-dax-endpoint

# plugins:
#   - serverless-webpack
#   - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.cjs
    includeModules: true
    packager: npm
    excludeFiles: '**/*.test.js'

  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
