apiVersion: v2
name: candlefish
description: Unified Candlefish AI Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: Candlefish AI Team
    email: deploy@candlefish.ai

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled

  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled

  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled

  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled

keywords:
  - candlefish
  - analytics
  - dashboard
  - paintbox
  - brand-portal
