app = "rtpm-api-candlefish"
primary_region = "sjc"

[build]
  dockerfile = "../../../apps/rtpm-api/Dockerfile"
  context = "../../../apps/rtpm-api"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/health"
    protocol = "http"
