global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'paintbox-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Paintbox Application Metrics
  - job_name: 'paintbox-app'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['paintbox-app.fly.dev:443']
        labels:
          service: 'paintbox'
          instance: 'production'
    scheme: https

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['paintbox-prod-db.internal:9187']
        labels:
          service: 'postgres'
          instance: 'production'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['paintbox-redis.internal:9121']
        labels:
          service: 'redis'
          instance: 'production'

  # Node Exporter (for system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['paintbox-app.internal:9100']
        labels:
          service: 'node'
          instance: 'production'

  # Fly.io metrics
  - job_name: 'fly-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['paintbox-app.fly.dev:9091']
        labels:
          service: 'fly'
          instance: 'production'
    scheme: https
