name: Claude Agents & Commands Sync

on:
  push:
    branches: [main]
    paths:
      - '.claude/agents/**'
      - '.claude/commands/**'
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      sync_target:
        description: 'Sync target (agents, commands, or both)'
        required: false
        default: 'both'
        type: choice
        options:
          - agents
          - commands
          - both

env:
  AGENTS_REPO: 'https://github.com/wshobson/agents.git'
  COMMANDS_REPO: 'https://github.com/wshobson/commands.git'

jobs:
  sync-claude-resources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "Claude Sync Bot"
          git config --global user.email "noreply@anthropic.com"

      - name: Setup Claude directories
        run: |
          mkdir -p .claude/agents .claude/commands

      - name: Add upstream remotes
        run: |
          # Add agents upstream
          cd .claude/agents
          git init
          git remote add upstream ${{ env.AGENTS_REPO }} || true
          cd ../..

          # Add commands upstream
          cd .claude/commands
          git init
          git remote add upstream ${{ env.COMMANDS_REPO }} || true
          cd ../..

      - name: Sync Agents Repository
        if: github.event.inputs.sync_target != 'commands'
        run: |
          echo "📚 Syncing agents repository..."
          cd .claude/agents

          # Fetch latest from upstream
          git fetch upstream main

          # Create worktree for clean merge
          git worktree add -b sync-agents ../agents-sync upstream/main

          # Copy files preserving git history
          cd ../agents-sync
          cp -r . ../agents/
          cd ../agents

          # Clean up worktree
          git worktree remove ../agents-sync

          # Stage changes
          git add -A

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Sync agents from upstream $(date +%Y-%m-%d)"
            echo "AGENTS_UPDATED=true" >> $GITHUB_ENV
          fi

          cd ../..

      - name: Sync Commands Repository
        if: github.event.inputs.sync_target != 'agents'
        run: |
          echo "🛠️ Syncing commands repository..."
          cd .claude/commands

          # Fetch latest from upstream
          git fetch upstream main

          # Create worktree for clean merge
          git worktree add -b sync-commands ../commands-sync upstream/main

          # Copy files preserving structure
          cd ../commands-sync
          cp -r . ../commands/
          cd ../commands

          # Clean up worktree
          git worktree remove ../commands-sync

          # Stage changes
          git add -A

          # Commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "🤖 Sync commands from upstream $(date +%Y-%m-%d)"
            echo "COMMANDS_UPDATED=true" >> $GITHUB_ENV
          fi

          cd ../..

      - name: Create Pull Request
        if: env.AGENTS_UPDATED == 'true' || env.COMMANDS_UPDATED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Update Claude agents and commands"
          title: "🤖 Claude Resources Sync - ${{ github.event.inputs.sync_target || 'both' }}"
          body: |
            ## Claude Resources Update

            This PR synchronizes the Claude agents and commands from their upstream repositories.

            ### Changes
            - ${{ env.AGENTS_UPDATED == 'true' && '✅ Agents repository updated' || '⏭️ No agent updates' }}
            - ${{ env.COMMANDS_UPDATED == 'true' && '✅ Commands repository updated' || '⏭️ No command updates' }}

            ### Reviewers
            - @aaron
            - @tyler

            ### Source Repositories
            - Agents: [wshobson/agents](https://github.com/wshobson/agents)
            - Commands: [wshobson/commands](https://github.com/wshobson/commands)

            ---
            *This PR was automatically generated by the Claude sync workflow.*
          branch: claude-sync-${{ github.run_number }}
          delete-branch: true
          reviewers: aaron,tyler
          assignees: patricksmith
