[build]
  command = "pnpm --filter paintbox build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"

[dev]
  framework = "next"
  command = "pnpm dev"
  targetPort = 3000
  port = 8888
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://api.paintbox.candlefish.ai/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
