# Base Netlify Configuration for Candlefish Sites
# This configuration should be extended by individual site configs

# Build Settings
[build]
  publish = "out"  # Override per site as needed

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--silent"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"
  GENERATE_SOURCEMAP = "false"
  NEXT_TELEMETRY_DISABLED = "1"

# Processing Settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  compress = true

[build.processing.images]
  compress = true

# Universal Plugins - Performance & Security

# 1. Lighthouse CI Plugin - Performance monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Performance budgets
    [plugins.inputs.thresholds]
      performance = 90
      accessibility = 95
      best-practices = 90
      seo = 90
      pwa = 80

    # Audit configuration
    [plugins.inputs.audits]
      [plugins.inputs.audits.metrics]
        first-contentful-paint = 1500
        largest-contentful-paint = 2500
        cumulative-layout-shift = 0.1
        total-blocking-time = 300

# 2. Security Headers Plugin
[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "out"
    exclude = ["/api/*", "/_next/*"]
    policies = [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.netlify.app https://*.candlefish.ai",
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "img-src 'self' data: https: blob:",
      "font-src 'self' https://fonts.gstatic.com",
      "connect-src 'self' https://*.candlefish.ai wss://*.candlefish.ai https://api.segment.io",
      "media-src 'self' blob:",
      "object-src 'none'",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "upgrade-insecure-requests"
    ]

# 3. Submit Sitemap Plugin
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://candlefish.ai"  # Override per site
    sitemapPath = "/sitemap.xml"
    providers = ["google", "bing"]

# 4. Cache Plugin for faster builds
[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs.nix]
    paths = [
      "node_modules/.cache",
      ".next/cache",
      ".netlify/cache"
    ]

# 5. Checklinks Plugin - Broken link detection
[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    entryPoints = ["*.html"]
    recursive = true
    pretty = true
    skipPatterns = ["/api/*", "mailto:*", "tel:*"]
    todoPatterns = []
    checkExternal = false
    followSourceMaps = false

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy-Report-Only = "default-src 'self'; report-uri https://candlefish.report-uri.com/r/d/csp/reportOnly"

# Cache Control Headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Edge Functions Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Block search engines from staging/preview deployments
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"  # Remove for production sites

# Redirect Rules
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# API proxy rules (customize per site)
[[redirects]]
  from = "/api/*"
  to = "https://api.candlefish.ai/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Forwarded-Host = "candlefish.ai"

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.included_files]
    patterns = ["data/*.json", "templates/*.html"]

# Development settings
[dev]
  framework = "next"  # Override per site
  port = 3000
  targetPort = 3000
  autoLaunch = false

# Environment contexts
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Analytics configuration
[analytics]
  provider = "netlify"

  [analytics.inputs]
    cookie_consent = false
    privacy_mode = true
    respect_dnt = true
