name: Sync Upstream Claude Resources

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      sync_target:
        description: 'Sync target (agents, commands, or both)'
        required: false
        default: 'both'
        type: choice
        options:
          - agents
          - commands
          - both

env:
  AGENTS_REPO: 'https://github.com/wshobson/agents.git'
  COMMANDS_REPO: 'https://github.com/wshobson/commands.git'

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "Claude Sync Bot"
          git config --global user.email "noreply@candlefish.com"

      - name: Setup Claude directories
        run: |
          mkdir -p .claude/agents .claude/commands .claude/tools .claude/workflows

      - name: Clone upstream repositories
        run: |
          # Clone agents repository
          if [ ! -d "upstream-agents" ]; then
            git clone ${{ env.AGENTS_REPO }} upstream-agents
          fi

          # Clone commands repository
          if [ ! -d "upstream-commands" ]; then
            git clone ${{ env.COMMANDS_REPO }} upstream-commands
          fi

      - name: Sync Agents Repository
        if: github.event.inputs.sync_target != 'commands'
        run: |
          echo "📚 Syncing agents repository..."

          # Copy agents preserving directory structure
          if [ -d "upstream-agents/agents" ]; then
            cp -r upstream-agents/agents/* .claude/agents/ 2>/dev/null || true
          elif [ -d "upstream-agents" ]; then
            # If agents are in root
            find upstream-agents -name "*.md" -maxdepth 1 -exec cp {} .claude/agents/ \;
          fi

          # Check for changes
          if ! git diff --quiet .claude/agents/; then
            echo "AGENTS_UPDATED=true" >> $GITHUB_ENV
          fi

      - name: Sync Commands Repository
        if: github.event.inputs.sync_target != 'agents'
        run: |
          echo "🛠️ Syncing commands repository..."

          # Copy commands
          if [ -d "upstream-commands/commands" ]; then
            cp -r upstream-commands/commands/* .claude/commands/ 2>/dev/null || true
          fi

          # Copy tools
          if [ -d "upstream-commands/tools" ]; then
            cp -r upstream-commands/tools/* .claude/tools/ 2>/dev/null || true
          fi

          # Copy workflows
          if [ -d "upstream-commands/workflows" ]; then
            cp -r upstream-commands/workflows/* .claude/workflows/ 2>/dev/null || true
          fi

          # Check for changes
          if ! git diff --quiet .claude/commands/ .claude/tools/ .claude/workflows/; then
            echo "COMMANDS_UPDATED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.AGENTS_UPDATED == 'true' || env.COMMANDS_UPDATED == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Update Claude agents and commands"
          title: "🤖 Claude Resources Sync - ${{ github.event.inputs.sync_target || 'both' }}"
          body: |
            ## Claude Resources Update

            This PR synchronizes the Claude agents and commands from their upstream repositories.

            ### Changes
            - ${{ env.AGENTS_UPDATED == 'true' && '✅ Agents repository updated' || '⏭️ No agent updates' }}
            - ${{ env.COMMANDS_UPDATED == 'true' && '✅ Commands repository updated' || '⏭️ No command updates' }}

            ### Reviewers
            - @aaron
            - @tyler

            ### Source Repositories
            - Agents: [wshobson/agents](https://github.com/wshobson/agents)
            - Commands: [wshobson/commands](https://github.com/wshobson/commands)

            ---
            *This PR was automatically generated by the Claude sync workflow.*
          branch: claude-sync-${{ github.run_number }}
          delete-branch: true
          reviewers: aaron,tyler
          assignees: patricksmith
