apiVersion: v1
kind: Namespace
metadata:
  name: rtpm-system
  labels:
    name: rtpm-system
    app.kubernetes.io/name: rtpm
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: rtpm-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rtpm-quota
  namespace: rtpm-system
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rtpm-limits
  namespace: rtpm-system
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container