apiVersion: v1
kind: ConfigMap
metadata:
  name: paintbox-config
  namespace: paintbox
data:
  # Database configurations
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"

  # Service ports
  ESTIMATES_PORT: "4002"
  CUSTOMERS_PORT: "4003"
  PROJECTS_PORT: "4004"
  INTEGRATIONS_PORT: "4005"
  ROUTER_PORT: "4100"
  FRONTEND_PORT: "3000"

  # Apollo configuration
  APOLLO_GRAPH_REF: "paintbox@main"

  # Application configuration
  NODE_ENV: "production"
  APP_NAME: "Paintbox"

  # CORS origins
  CORS_ORIGINS: "https://paintbox.candlefish.ai,https://app.paintbox.candlefish.ai"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paintbox-staging-config
  namespace: paintbox-staging
data:
  # Database configurations
  POSTGRES_PORT: "5432"
  REDIS_PORT: "6379"

  # Service ports
  ESTIMATES_PORT: "4002"
  CUSTOMERS_PORT: "4003"
  PROJECTS_PORT: "4004"
  INTEGRATIONS_PORT: "4005"
  ROUTER_PORT: "4100"
  FRONTEND_PORT: "3000"

  # Apollo configuration
  APOLLO_GRAPH_REF: "paintbox@staging"

  # Application configuration
  NODE_ENV: "staging"
  APP_NAME: "Paintbox Staging"

  # CORS origins
  CORS_ORIGINS: "https://staging.paintbox.candlefish.ai"
