{{- if and .Values.website.enabled .Values.website.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.website.name }}-hpa{{ if .Values.global.canary }}-canary{{ end }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.website.name }}
    component: frontend
    environment: {{ .Values.global.environment }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.website.name }}{{ if .Values.global.canary }}-canary{{ end }}{{ if ne .Values.global.color "blue" }}-{{ .Values.global.color }}{{ end }}
  minReplicas: {{ .Values.website.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.website.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.website.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.website.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.website.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.website.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}
