{{- if .Values.website.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.name }}-service{{ if .Values.global.canary }}-canary{{ end }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.website.name }}
    component: frontend
    environment: {{ .Values.global.environment }}
    {{- if .Values.global.canary }}
    version: canary
    {{- end }}
    {{- if .Values.global.color }}
    color: {{ .Values.global.color }}
    {{- end }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-unhealthy-threshold: "3"
spec:
  type: {{ .Values.website.service.type }}
  ports:
    - port: {{ .Values.website.service.port }}
      targetPort: {{ .Values.website.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.website.name }}
    {{- if .Values.global.canary }}
    version: canary
    {{- else }}
    {{- if .Values.global.color }}
    color: {{ .Values.global.color }}
    {{- end }}
    {{- end }}
{{- end }}
