version: '3.8'

# Production overrides
services:
  # Use production builds for all services
  estimates-subgraph:
    build:
      target: production
    volumes: []
    environment:
      NODE_ENV: production
      DATABASE_URL: ${ESTIMATES_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

  customers-subgraph:
    build:
      target: production
    volumes: []
    environment:
      NODE_ENV: production
      DATABASE_URL: ${CUSTOMERS_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

  projects-subgraph:
    build:
      target: production
    volumes: []
    environment:
      NODE_ENV: production
      DATABASE_URL: ${PROJECTS_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

  integrations-subgraph:
    build:
      target: production
    volumes: []
    environment:
      NODE_ENV: production
      DATABASE_URL: ${INTEGRATIONS_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

  frontend:
    build:
      target: production
    ports:
      - "3000:3000"
    volumes: []
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_WS_URL: ${VITE_WS_URL}

  # Remove local databases in production (use managed services)
  db-estimates:
    deploy:
      replicas: 0

  db-customers:
    deploy:
      replicas: 0

  db-projects:
    deploy:
      replicas: 0

  db-integrations:
    deploy:
      replicas: 0

  # Use managed Redis in production
  redis:
    deploy:
      replicas: 0
