// Auto-generated TypeScript models from Excel analysis
// Generated by Excel Expert Analysis Tool

export interface ExcelFormula {
  sheet: string;
  cell: string;
  formula: string;
  category: FormulaCategory;
  dependencies: string[];
  row: number;
  column: number;
}

export type FormulaCategory =
  | 'Financial'
  | 'Lookup'
  | 'Statistical'
  | 'Math'
  | 'Logical'
  | 'Text'
  | 'DateTime'
  | 'Arithmetic'
  | 'Other';

export interface NamedRange {
  name: string;
  scope?: string;
  destinations: Array<{
    sheet: string;
    range: string;
  }>;
  value?: string;
}

export interface SheetInfo {
  max_row: number;
  max_column: number;
  cell_count: number;
}

export interface ExcelAnalysis {
  metadata: {
    excel_file: string;
    total_formulas: number;
    sheet_count: number;
    sheets_info: Record<string, SheetInfo>;
    category_summary: Record<FormulaCategory, number>;
  };
  named_ranges: Record<string, NamedRange>;
  formulas_by_sheet: Record<string, ExcelFormula[]>;
  complex_formulas: ExcelFormula[];
  dependencies: Record<string, string[]>;
}
