# Optimized Fly.io Configuration
app = "paintbox-app"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile.fly.optimized"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  NEXT_PUBLIC_API_URL = "https://paintbox-app.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024
