# Simple Fly.io configuration for Paintbox
app = "paintbox-app"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
  release_command = "echo 'Release command placeholder'"
  strategy = "rolling"

[build]
  dockerfile = "Dockerfile.fly.minimal"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_APP_VERSION = "1.0.0"
  NEXT_PUBLIC_API_URL = "https://paintbox-app.fly.dev"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
