#!/bin/bash
# Demo script to showcase the new navigation system

echo "🐠 CANDLEFISH ENHANCED NAVIGATION DEMO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Your terminal now has comprehensive navigation to ALL projects!"
echo ""
echo "🔥 TRY THESE COMMANDS:"
echo ""
echo "  cfnav         - Show the full navigation menu"
echo "  cfstatus      - Check git status of active projects"
echo "  cfrecent      - Jump to your most recent work"
echo ""
echo "🎯 ACTIVE PROJECT SHORTCUTS:"
echo ""
echo "  cfweb         - Jump to brand website (active dev)"
echo "  cfpaint       - Jump to Paintbox platform"
echo "  cfpaintapi    - Jump to Paintbox API routes"
echo "  cfclark       - Jump to Clark County scraper"
echo "  cfibm         - Jump to IBM Watson portfolio"
echo ""
echo "💼 BUSINESS PROJECTS:"
echo ""
echo "  cffogg        - Fogg calendar system"
echo "  cfcrown       - Crown Trophy project"
echo "  cfpromoter    - PromoterOS platform"
echo "  cfslack       - Slack integration"
echo "  cfhighline    - 5470 S Highline valuation"
echo ""
echo "🚀 QUICK ACTIONS:"
echo ""
echo "  cfpaintedit   - Open Paintbox in your editor"
echo "  cfpainttest   - Run Paintbox tests"
echo "  cfpaintdeploy - Deploy Paintbox"
echo ""
echo "📍 Tab completion works! Try typing 'cf' and hit TAB twice"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Full reference saved to: NAVIGATION_QUICK_REFERENCE.md"
echo ""
