# PromoterOS API - Fly.io Configuration
app = "promoteros-api"
primary_region = "sea"  # Seattle region for low latency to west coast users
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  NODE_ENV = "production"
  PORT = "3002"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/healthz"
  timeout = "10s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"

[metrics]
  port = 9091
  path = "/metrics"
