# Override file for local development
# This file extends docker-compose.yml with development-specific settings

version: '3.8'

services:
  website:
    # Enable hot reloading for development
    command: npm run dev -- --host 0.0.0.0
    environment:
      - VITE_HMR_PORT=3000
      - VITE_HMR_HOST=localhost
    # Additional volume mounts for faster development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/coverage
    # Development debugging ports
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debugger

  redis:
    # Development Redis configuration
    volumes:
      - redis-dev-data:/data
    # Enable Redis CLI access
    ports:
      - "6379:6379"

volumes:
  redis-dev-data:
    driver: local