[build]
  publish = "dist"
  
# TikTok verification files - serve as static files
[[redirects]]
  from = "/tiktok*.txt"
  to = "/tiktok*.txt"
  status = 200
  force = false

# TikTok OAuth callback - serve as static files
[[redirects]]
  from = "/auth/tiktok/*"
  to = "/auth/tiktok/:splat"
  status = 200
  force = false

# .well-known directory for domain verification
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = false

# Main SPA redirect - comes last with force = false to allow static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
