# Prometheus alerting rules for Candlefish Collaboration System
groups:
  # Application-specific alerts
  - name: collaboration-application
    rules:
    # GraphQL API Alerts
    - alert: GraphQLAPIHighErrorRate
      expr: |
        (
          rate(collaboration_graphql_errors_total[5m]) /
          rate(collaboration_graphql_requests_total[5m])
        ) * 100 > 5
      for: 2m
      labels:
        severity: warning
        service: graphql-api
        component: collaboration
      annotations:
        summary: "High error rate in GraphQL API"
        description: "GraphQL API error rate is {{ $value }}% for the last 5 minutes"
        runbook_url: "https://runbook.candlefish.ai/graphql-api-errors"

    - alert: GraphQLAPIHighLatency
      expr: |
        histogram_quantile(0.95, rate(collaboration_graphql_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: graphql-api
        component: collaboration
      annotations:
        summary: "High latency in GraphQL API"
        description: "95th percentile latency is {{ $value }}s for the last 5 minutes"
        runbook_url: "https://runbook.candlefish.ai/graphql-api-latency"

    - alert: GraphQLAPIDown
      expr: up{job="collaboration-graphql-api"} == 0
      for: 1m
      labels:
        severity: critical
        service: graphql-api
        component: collaboration
      annotations:
        summary: "GraphQL API is down"
        description: "GraphQL API has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/service-down"

    # WebSocket Service Alerts
    - alert: WebSocketHighConnectionDrops
      expr: |
        rate(collaboration_websocket_connections_dropped_total[5m]) > 10
      for: 2m
      labels:
        severity: warning
        service: websocket
        component: collaboration
      annotations:
        summary: "High WebSocket connection drops"
        description: "WebSocket connections are dropping at {{ $value }} per second"
        runbook_url: "https://runbook.candlefish.ai/websocket-drops"

    - alert: WebSocketHighConnectionCount
      expr: |
        collaboration_websocket_active_connections > 8000
      for: 5m
      labels:
        severity: warning
        service: websocket
        component: collaboration
      annotations:
        summary: "High WebSocket connection count"
        description: "Active WebSocket connections: {{ $value }}"
        runbook_url: "https://runbook.candlefish.ai/websocket-scaling"

    - alert: WebSocketServiceDown
      expr: up{job="collaboration-websocket"} == 0
      for: 1m
      labels:
        severity: critical
        service: websocket
        component: collaboration
      annotations:
        summary: "WebSocket service is down"
        description: "WebSocket service has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/service-down"

    # Document Service Alerts
    - alert: DocumentServiceHighLatency
      expr: |
        histogram_quantile(0.95, rate(collaboration_document_operation_duration_seconds_bucket[5m])) > 5
      for: 5m
      labels:
        severity: warning
        service: document
        component: collaboration
      annotations:
        summary: "High latency in Document Service"
        description: "95th percentile operation latency is {{ $value }}s"
        runbook_url: "https://runbook.candlefish.ai/document-latency"

    - alert: DocumentConflictResolutionHigh
      expr: |
        rate(collaboration_document_conflicts_total[5m]) > 1
      for: 10m
      labels:
        severity: warning
        service: document
        component: collaboration
      annotations:
        summary: "High document conflict resolution rate"
        description: "Document conflicts are occurring at {{ $value }} per second"
        runbook_url: "https://runbook.candlefish.ai/document-conflicts"

    - alert: DocumentServiceDown
      expr: up{job="collaboration-document"} == 0
      for: 1m
      labels:
        severity: critical
        service: document
        component: collaboration
      annotations:
        summary: "Document service is down"
        description: "Document service has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/service-down"

    # Frontend Application Alerts
    - alert: FrontendHighErrorRate
      expr: |
        (
          rate(http_requests_total{status=~"5.."}[5m]) /
          rate(http_requests_total[5m])
        ) * 100 > 5
      for: 2m
      labels:
        severity: warning
        service: frontend
        component: collaboration
      annotations:
        summary: "High error rate in frontend application"
        description: "Frontend error rate is {{ $value }}% for the last 5 minutes"
        runbook_url: "https://runbook.candlefish.ai/frontend-errors"

    - alert: FrontendDown
      expr: up{job="nextjs-app"} == 0
      for: 1m
      labels:
        severity: critical
        service: frontend
        component: collaboration
      annotations:
        summary: "Frontend application is down"
        description: "Frontend application has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/service-down"

  # Database alerts
  - name: collaboration-database
    rules:
    - alert: PostgreSQLDown
      expr: up{job="postgresql-exporter"} == 0
      for: 1m
      labels:
        severity: critical
        service: postgresql
        component: database
      annotations:
        summary: "PostgreSQL is down"
        description: "PostgreSQL database has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/database-down"

    - alert: PostgreSQLHighConnections
      expr: |
        (
          pg_stat_activity_count /
          pg_settings_max_connections
        ) * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: postgresql
        component: database
      annotations:
        summary: "PostgreSQL high connection usage"
        description: "PostgreSQL connection usage is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/database-connections"

    - alert: PostgreSQLSlowQueries
      expr: |
        rate(pg_stat_activity_max_tx_duration{datname="collaboration_db"}[5m]) > 60
      for: 5m
      labels:
        severity: warning
        service: postgresql
        component: database
      annotations:
        summary: "PostgreSQL slow queries detected"
        description: "Slow query detected with duration {{ $value }}s"
        runbook_url: "https://runbook.candlefish.ai/database-performance"

    - alert: PostgreSQLReplicationLag
      expr: |
        pg_replication_lag > 10
      for: 5m
      labels:
        severity: warning
        service: postgresql
        component: database
      annotations:
        summary: "PostgreSQL replication lag is high"
        description: "Replication lag is {{ $value }}s"
        runbook_url: "https://runbook.candlefish.ai/database-replication"

    - alert: PostgreSQLDiskSpaceHigh
      expr: |
        (
          (pg_database_size_bytes{datname="collaboration_db"} / 1024 / 1024 / 1024) /
          100
        ) * 100 > 85
      for: 10m
      labels:
        severity: warning
        service: postgresql
        component: database
      annotations:
        summary: "PostgreSQL disk usage is high"
        description: "Database size is {{ $value }}GB (>85% of allocated space)"
        runbook_url: "https://runbook.candlefish.ai/database-storage"

  # Redis alerts
  - name: collaboration-redis
    rules:
    - alert: RedisDown
      expr: up{job="redis-exporter"} == 0
      for: 1m
      labels:
        severity: critical
        service: redis
        component: cache
      annotations:
        summary: "Redis is down"
        description: "Redis has been down for more than 1 minute"
        runbook_url: "https://runbook.candlefish.ai/redis-down"

    - alert: RedisHighMemoryUsage
      expr: |
        (
          redis_memory_used_bytes /
          redis_memory_max_bytes
        ) * 100 > 90
      for: 5m
      labels:
        severity: warning
        service: redis
        component: cache
      annotations:
        summary: "Redis high memory usage"
        description: "Redis memory usage is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/redis-memory"

    - alert: RedisHighConnections
      expr: |
        redis_connected_clients > 500
      for: 5m
      labels:
        severity: warning
        service: redis
        component: cache
      annotations:
        summary: "Redis high connection count"
        description: "Redis has {{ $value }} connected clients"
        runbook_url: "https://runbook.candlefish.ai/redis-connections"

    - alert: RedisSlowQueries
      expr: |
        redis_slowlog_length > 10
      for: 5m
      labels:
        severity: warning
        service: redis
        component: cache
      annotations:
        summary: "Redis slow queries detected"
        description: "Redis slowlog has {{ $value }} entries"
        runbook_url: "https://runbook.candlefish.ai/redis-performance"

    - alert: RedisReplicationLag
      expr: |
        redis_master_last_io_seconds_ago > 30
      for: 2m
      labels:
        severity: warning
        service: redis
        component: cache
      annotations:
        summary: "Redis replication lag is high"
        description: "Redis replica hasn't communicated with master for {{ $value }}s"
        runbook_url: "https://runbook.candlefish.ai/redis-replication"

  # Infrastructure alerts
  - name: collaboration-infrastructure
    rules:
    # Kubernetes cluster alerts
    - alert: KubernetesNodeDown
      expr: up{job="kubernetes-nodes"} == 0
      for: 5m
      labels:
        severity: critical
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Kubernetes node is down"
        description: "Kubernetes node {{ $labels.instance }} has been down for more than 5 minutes"
        runbook_url: "https://runbook.candlefish.ai/node-down"

    - alert: KubernetesNodeHighCPU
      expr: |
        (
          1 - (
            avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance)
          )
        ) * 100 > 80
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Kubernetes node high CPU usage"
        description: "Node {{ $labels.instance }} CPU usage is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/node-cpu"

    - alert: KubernetesNodeHighMemory
      expr: |
        (
          1 - (
            node_memory_MemAvailable_bytes /
            node_memory_MemTotal_bytes
          )
        ) * 100 > 90
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Kubernetes node high memory usage"
        description: "Node {{ $labels.instance }} memory usage is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/node-memory"

    - alert: KubernetesNodeHighDiskUsage
      expr: |
        (
          1 - (
            node_filesystem_avail_bytes{mountpoint="/"} /
            node_filesystem_size_bytes{mountpoint="/"}
          )
        ) * 100 > 85
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Kubernetes node high disk usage"
        description: "Node {{ $labels.instance }} disk usage is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/node-disk"

    # Pod alerts
    - alert: KubernetesPodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total[5m]) * 60 * 5 > 5
      for: 5m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
        runbook_url: "https://runbook.candlefish.ai/pod-crash"

    - alert: KubernetesPodNotReady
      expr: |
        kube_pod_status_ready{condition="false"} == 1
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Pod not ready"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been not ready for more than 10 minutes"
        runbook_url: "https://runbook.candlefish.ai/pod-not-ready"

    - alert: KubernetesDeploymentReplicasMismatch
      expr: |
        kube_deployment_spec_replicas != kube_deployment_status_available_replicas
      for: 10m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "Deployment replicas mismatch"
        description: "Deployment {{ $labels.namespace }}/{{ $labels.deployment }} has {{ $value }} available replicas, expected {{ $labels.spec_replicas }}"
        runbook_url: "https://runbook.candlefish.ai/deployment-replicas"

    # HPA alerts
    - alert: KubernetesHPAScaleCapability
      expr: |
        kube_horizontalpodautoscaler_status_current_replicas >= kube_horizontalpodautoscaler_spec_max_replicas
      for: 5m
      labels:
        severity: warning
        service: kubernetes
        component: infrastructure
      annotations:
        summary: "HPA at max scale"
        description: "HPA {{ $labels.namespace }}/{{ $labels.horizontalpodautoscaler }} is at maximum scale"
        runbook_url: "https://runbook.candlefish.ai/hpa-max-scale"

  # Business logic alerts
  - name: collaboration-business
    rules:
    - alert: HighUserSessionDrops
      expr: |
        rate(collaboration_user_sessions_dropped_total[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: collaboration
        component: business
      annotations:
        summary: "High user session drop rate"
        description: "User sessions are dropping at {{ $value }} per second"
        runbook_url: "https://runbook.candlefish.ai/user-sessions"

    - alert: CollaborationConflictsHigh
      expr: |
        rate(collaboration_merge_conflicts_total[5m]) > 0.5
      for: 10m
      labels:
        severity: warning
        service: collaboration
        component: business
      annotations:
        summary: "High collaboration conflict rate"
        description: "Collaboration conflicts occurring at {{ $value }} per second"
        runbook_url: "https://runbook.candlefish.ai/collaboration-conflicts"

    - alert: DocumentSaveFailuresHigh
      expr: |
        (
          rate(collaboration_document_saves_failed_total[5m]) /
          rate(collaboration_document_saves_total[5m])
        ) * 100 > 1
      for: 5m
      labels:
        severity: warning
        service: collaboration
        component: business
      annotations:
        summary: "High document save failure rate"
        description: "Document save failure rate is {{ $value }}%"
        runbook_url: "https://runbook.candlefish.ai/document-saves"

    - alert: RealTimeSyncDelayHigh
      expr: |
        histogram_quantile(0.95, rate(collaboration_sync_delay_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: collaboration
        component: business
      annotations:
        summary: "High real-time sync delay"
        description: "95th percentile sync delay is {{ $value }}s"
        runbook_url: "https://runbook.candlefish.ai/sync-delay"
