apiVersion: v1
kind: Namespace
metadata:
  name: system-analyzer
  labels:
    name: system-analyzer
    environment: production
    app.kubernetes.io/name: system-analyzer
    app.kubernetes.io/version: "1.0.0"
---
# Network policies for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: system-analyzer-network-policy
  namespace: system-analyzer
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: system-analyzer
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
  egress:
  - {}  # Allow all egress traffic
---
# Resource quota to prevent resource exhaustion
apiVersion: v1
kind: ResourceQuota
metadata:
  name: system-analyzer-quota
  namespace: system-analyzer
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    persistentvolumeclaims: "10"
    services: "10"
