# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Main package.json dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    assignees:
      - "paintbox-maintainers"
    reviewers:
      - "paintbox-security-team"
    labels:
      - "dependencies"
      - "auto-update"
    versioning-strategy: increase
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Critical dependencies that need manual review
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps"
      include: "scope"

  # Apollo GraphQL subproject
  - package-ecosystem: "npm"
    directory: "/apollo-graphos"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "apollo-graphos"
      - "auto-update"

  # Frontend subproject
  - package-ecosystem: "npm"
    directory: "/apollo-graphos/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
      - "auto-update"

  # Subgraph estimates
  - package-ecosystem: "npm"
    directory: "/apollo-graphos/subgraph-estimates"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "subgraph"
      - "auto-update"

  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/mobile/PaintboxMobile"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "mobile"
      - "auto-update"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
      - "auto-update"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-update"

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "terraform"
      - "auto-update"
