apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-editor
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: collaboration-editor
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: collaboration-editor
      component: frontend
  template:
    metadata:
      labels:
        app: collaboration-editor
        component: frontend
        app.kubernetes.io/name: candlefish-collaboration
        app.kubernetes.io/component: collaboration-editor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: collaboration-editor
        image: candlefish/collaboration-editor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        # GraphQL API endpoints
        - name: NEXT_PUBLIC_GRAPHQL_URL
          value: "https://api.candlefish.ai/graphql"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://ws.candlefish.ai/graphql"
        # Internal service URLs (for SSR)
        - name: GRAPHQL_API_URL
          value: "http://graphql-api-service:4000/graphql"
        - name: WS_API_URL
          value: "ws://websocket-service:4001/graphql"
        - name: DOCUMENT_API_URL
          value: "http://document-service:4003"
        # Authentication
        - name: NEXTAUTH_URL
          value: "https://editor.candlefish.ai"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: collaboration-secrets
              key: JWT_SECRET
        # Performance optimizations
        - name: NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING
          value: "true"
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: collaboration-secrets
              key: SENTRY_DSN
              optional: true
        # Feature flags
        - name: NEXT_PUBLIC_ENABLE_REAL_TIME_CURSORS
          value: "true"
        - name: NEXT_PUBLIC_ENABLE_COLLABORATIVE_COMMENTS
          value: "true"
        - name: NEXT_PUBLIC_ENABLE_VERSION_HISTORY
          value: "true"
        - name: NEXT_PUBLIC_ENABLE_OFFLINE_MODE
          value: "true"
        # CDN and asset configuration
        - name: NEXT_PUBLIC_CDN_URL
          value: "https://cdn.candlefish.ai"
        - name: NEXT_PUBLIC_ASSETS_PREFIX
          value: "/static"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: next-cache
          mountPath: /app/.next/cache
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

      volumes:
      - name: tmp
        emptyDir: {}
      - name: next-cache
        emptyDir:
          sizeLimit: 1Gi

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - collaboration-editor
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: collaboration-editor-service
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: collaboration-editor
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: http
    protocol: TCP
  selector:
    app: collaboration-editor
    component: frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: collaboration-editor-hpa
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: collaboration-editor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collaboration-editor
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: collaboration-editor-pdb
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: collaboration-editor
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: collaboration-editor
      component: frontend

---
# Service for static asset serving (CDN integration)
apiVersion: v1
kind: Service
metadata:
  name: collaboration-assets-service
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: assets
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: "443"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
  selector:
    app: collaboration-editor
    component: frontend
