apiVersion: v1
kind: Secret
metadata:
  name: collaboration-secrets
  namespace: collaboration
  labels:
    app.kubernetes.io/name: candlefish-collaboration
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://collaboration_user:${DB_PASSWORD}@postgres-service:5432/collaboration_db"

  # Redis
  REDIS_URL: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"
  REDIS_CLUSTER_URLS: "redis://:${REDIS_PASSWORD}@redis-service:6379/0"

  # JWT
  JWT_SECRET: "${JWT_SECRET}"
  JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"

  # Encryption
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"

  # AWS
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION: "us-east-1"

  # S3 for File Storage
  S3_BUCKET_NAME: "${S3_BUCKET_NAME}"
  S3_REGION: "us-east-1"

  # External APIs
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

  # WebSocket Auth
  WS_AUTH_SECRET: "${WS_AUTH_SECRET}"

  # Monitoring
  SENTRY_DSN: "${SENTRY_DSN}"

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: collaboration
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collaboration-external-secrets
  namespace: collaboration
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: collaboration-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: candlefish/collaboration/database-url
  - secretKey: REDIS_URL
    remoteRef:
      key: candlefish/collaboration/redis-url
  - secretKey: JWT_SECRET
    remoteRef:
      key: candlefish/collaboration/jwt-secret
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: candlefish/collaboration/encryption-key
