apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimates-subgraph
  namespace: paintbox
  labels:
    app: estimates-subgraph
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: estimates-subgraph
  template:
    metadata:
      labels:
        app: estimates-subgraph
        version: v1
    spec:
      containers:
      - name: estimates-subgraph
        image: paintbox/estimates-subgraph:latest
        ports:
        - containerPort: 4002
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: paintbox-config
              key: ESTIMATES_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: paintbox-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: paintbox-secrets
              key: ESTIMATES_DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: paintbox-secrets
              key: REDIS_URL
        - name: APOLLO_KEY
          valueFrom:
            secretKeyRef:
              name: paintbox-secrets
              key: APOLLO_KEY
        - name: APOLLO_GRAPH_REF
          valueFrom:
            configMapKeyRef:
              name: paintbox-config
              key: APOLLO_GRAPH_REF
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: estimates-subgraph
  namespace: paintbox
  labels:
    app: estimates-subgraph
spec:
  type: ClusterIP
  ports:
  - port: 4002
    targetPort: 4002
    protocol: TCP
    name: http
  selector:
    app: estimates-subgraph
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: estimates-subgraph-pdb
  namespace: paintbox
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: estimates-subgraph
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: estimates-subgraph-hpa
  namespace: paintbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: estimates-subgraph
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
