name: Deploy RTPM (Fly.io)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/rtpm-api/**'
      - 'deployment/rtpm-dashboard/**'
      - '.github/workflows/deploy-rtpm.yml'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}
      - name: Load secrets from AWS SSM and set Fly secrets
        env:
          APP: rtpm-api-candlefish
        run: |
          set -euo pipefail
          # Expected SSM params
          PARAMS=(DATABASE_URL REDIS_URL JWT_SECRET SECRET_KEY CORS_ORIGINS)
          for key in "${PARAMS[@]}"; do
            val=$(aws ssm get-parameter --name "/candlefish/prod/rtpm-api/${key}" --with-decryption --query Parameter.Value --output text || true)
            if [ -n "${val}" ] && [ "${val}" != "None" ]; then
              echo "Setting ${key}"
              echo "${key}=${val}" >> .fly.env
            fi
          done
          if [ -f .fly.env ]; then
            flyctl secrets set --app "$APP" $(cat .fly.env | xargs) || true
          fi
      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        working-directory: ./deployment/fly/rtpm-api
        run: |
          flyctl deploy --remote-only --build-arg BUILDKIT_PROGRESS=plain

  deploy-dashboard:
    runs-on: ubuntu-latest
    needs: [deploy-api]
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}
      - name: Set Fly secrets for dashboard
        env:
          APP: rtpm-dashboard-candlefish
        run: |
          set -euo pipefail
          # Pull API host if stored in SSM
          API_HOST=$(aws ssm get-parameter --name "/candlefish/prod/rtpm-dashboard/API_HOST" --with-decryption --query Parameter.Value --output text || echo "api.candlefish.ai")
          flyctl secrets set --app "$APP" VITE_API_URL="https://${API_HOST}" VITE_WS_URL="wss://${API_HOST}" || true
      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Dashboard
        working-directory: ./deployment/fly/rtpm-dashboard
        run: |
          flyctl deploy --remote-only --build-arg BUILDKIT_PROGRESS=plain
