name: Documentation Link Check

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-linkcheck.yml'
  pull_request:
    paths:
      - 'docs/**'
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: '--verbose --no-progress docs/**/*.md'
          fail: true

      - name: Upload Link Check Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-results
          path: lychee-out.md
