name: Security Scan

on:
  push:
    branches: [main, development]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

concurrency:
  group: security-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_ENABLE_SUMMARY: true

      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
        continue-on-error: true

  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ecosystem: [npm, pip]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: matrix.ecosystem == 'npm'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        if: matrix.ecosystem == 'pip'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: NPM Audit
        if: matrix.ecosystem == 'npm'
        run: |
          npm ci --include=dev
          npm audit --audit-level=moderate || true
          
      - name: Python Safety Check
        if: matrix.ecosystem == 'pip'
        run: |
          pip install safety
          safety check --json || true

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'python']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'schedule'
    strategy:
      matrix:
        dockerfile: 
          - Dockerfile
          - apps/rtpm-api/Dockerfile
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: ${{ matrix.dockerfile }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [gitleaks, dependency-check, codeql]
    if: always()
    
    steps:
      - name: Security Check Summary
        run: |
          echo "## Security Scan Complete"
          echo "- Secret Scanning: ${{ needs.gitleaks.result }}"
          echo "- Dependency Check: ${{ needs.dependency-check.result }}"
          echo "- CodeQL Analysis: ${{ needs.codeql.result }}"
          
          if [[ "${{ needs.gitleaks.result }}" == "failure" ]] || \
             [[ "${{ needs.dependency-check.result }}" == "failure" ]] || \
             [[ "${{ needs.codeql.result }}" == "failure" ]]; then
            echo "⚠️ Security issues detected. Please review the findings above."
            exit 1
          else
            echo "✅ All security checks passed!"
          fi